// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBT33Zj-NxUiXMOe6NXJ63byt3naov8EMk',
    appId: '1:950220633637:web:cbedda9d0c710f65f731cc',
    messagingSenderId: '950220633637',
    projectId: 'swapit-fb0f8',
    authDomain: 'swapit-fb0f8.firebaseapp.com',
    storageBucket: 'swapit-fb0f8.appspot.com',
    measurementId: 'G-DPC4XCTFPP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9SC3GbGUYJWlKcv_QDiInNECCGm5iAIk',
    appId: '1:950220633637:android:0111fbaf2c40116bf731cc',
    messagingSenderId: '950220633637',
    projectId: 'swapit-fb0f8',
    storageBucket: 'swapit-fb0f8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCe1s0kCwMiW2SVNDOv59RdgRvKulLcg_E',
    appId: '1:950220633637:ios:e4420312ea5b16adf731cc',
    messagingSenderId: '950220633637',
    projectId: 'swapit-fb0f8',
    storageBucket: 'swapit-fb0f8.appspot.com',
    iosClientId: '950220633637-1lrg08dgf86td95p9820ltks5lnaoaud.apps.googleusercontent.com',
    iosBundleId: 'com.example.swapit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCe1s0kCwMiW2SVNDOv59RdgRvKulLcg_E',
    appId: '1:950220633637:ios:e4420312ea5b16adf731cc',
    messagingSenderId: '950220633637',
    projectId: 'swapit-fb0f8',
    storageBucket: 'swapit-fb0f8.appspot.com',
    iosClientId: '950220633637-1lrg08dgf86td95p9820ltks5lnaoaud.apps.googleusercontent.com',
    iosBundleId: 'com.example.swapit',
  );
}
